# GitHub Actions CI/CD Pipeline for RestAssured Framework
name: API Test Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  MAVEN_OPTS: -Xmx2048m -Xms512m

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    strategy:
      matrix:
        java-version: [17]
        test-suite: [smoke, regression]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Verify Java Installation
      run: |
        java -version
        mvn -version

    - name: Set environment variables
      run: |
        echo "env=dev" >> $GITHUB_ENV
        echo "suite=${{ matrix.test-suite }}" >> $GITHUB_ENV

    - name: Run Maven Clean
      run: mvn clean

    - name: Run ${{ matrix.test-suite }} Tests
      run: |
        mvn test \
          -Denv=dev \
          -P${{ matrix.test-suite }} \
          -Dmaven.test.failure.ignore=false \
          -Dparallel.threads=2 \
          --batch-mode \
          --no-transfer-progress
      continue-on-error: false

    - name: Generate Allure Report
      if: always()
      run: |
        mvn allure:report
      continue-on-error: true

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.test-suite }}-java-${{ matrix.java-version }}
        path: |
          target/surefire-reports/
          target/allure-results/
          target/site/allure-maven-plugin/
          test-output/
          logs/
        retention-days: 7

    - name: Upload Extent Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: extent-reports-${{ matrix.test-suite }}-java-${{ matrix.java-version }}
        path: test-output/extent-reports/
        retention-days: 7

    - name: Publish Test Results
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Test Results - ${{ matrix.test-suite }} - Java ${{ matrix.java-version }}
        path: target/surefire-reports/*.xml
        reporter: java-junit

  # Aggregate results from all test suites
  aggregate-results:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Display structure of downloaded files
      run: ls -la
      
    - name: Summary
      run: |
        echo "## Test Execution Summary" >> $GITHUB_STEP_SUMMARY
        echo "All test suites have been executed." >> $GITHUB_STEP_SUMMARY
        echo "Check individual job results for detailed information." >> $GITHUB_STEP_SUMMARY
